### ISSUE TITLE
Hi Saikat Basak

### ISSUE THREAD

**Issue by mjm522** [saikatbsk/Vincent-AI-Artist#1]
Hey saw your post on Google+, I have put up the code for running.
Let me see what happens. 

Using Theano backend.
Model loaded.
('Starting iteration', 1)....

However I would like to ask you add `pillow or pil` (else `from scipy.misc import imread`wont work)to your dependencies.

**Comment by saikatbsk** [comment]
Thanks for pointing out the dependency issue. I'll fix that.

**Comment by mjm522** [comment]
('Current loss value: ', array(77392.1875, dtype=float32))
Traceback (most recent call last):
  File "main.py", line 304, in <module>
    img = deprocess(x.reshare((3, img_width, img_height)))
AttributeError: 'numpy.ndarray' object has no attribute 'reshare'

**Comment by saikatbsk** [comment]
That would be the silliest typo ever. It would be x.reshape(). Fixed. Please try now.
