### ISSUE TITLE
Problem Loading Weights

### ISSUE THREAD

**Issue by Naresh1318** [saikatbsk/Vincent-AI-Artist#2]
Traceback (most recent call last):
File "/Users/MyName/Desktop/Artist/Network.py", line 292, in 
load_weights(weights_path, model)
File "/Users/MyName/Desktop/Artist/Network.py", line 85, in load_weights
model.layers[k].set_weights(weights)
File "/Users/MyName/anaconda/lib/python3.5/site-packages/keras/engine/topology.py", line 889, in set_weights
'provided weight shape ' + str(w.shape))
Exception: Layer weight shape (3, 3, 512, 64) not compatible with provided weight shape (64, 3, 3, 3)

**Comment by saikatbsk** [comment]
Have you downloaded the VGG16 file? It contains the weights.

**Comment by Naresh1318** [comment]
Yes I have, it's in the same folder as that which contains the script. It's **not** giving the error : Model weights not found (see "weights_path" variable in script) which is raised when the weights path isn't found.

**Comment by saikatbsk** [comment]
mail (or use imgur) me the images you are using.

**Comment by saikatbsk** [comment]
Does the issue persist? If not then I'll close this.

**Comment by Naresh1318** [comment]
Ok, I found this : 'The code and the provided "vgg16_weights.h5" file follow Theano conventions for dimension ordering. Due to recent updates in the libraries, this won't work. Using a Theano backend in its entirety also won't work without modifying the rest of the code. This is perhaps the quickest way to solve this issue.'

https://github.com/llSourcell/AI_Artist/pull/6/commits/36ca7dfe81e44561552d0820ff71f5eb91fde75d

So adding this line after importing keras backend fixed the error : K.set_image_dim_ordering('th')
